### ISSUE TITLE
copyright of t/etc/netbsd-*/release

### ISSUE THREAD

**Issue by carandraug** [Tux/System-Info#1]
The `t/etc/netbsd-*/release` have a copyright notice as such:

    Copyright (c) 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005,
        2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015
        The NetBSD Foundation, Inc.  All rights reserved.
    Copyright (c) 1982, 1986, 1989, 1991, 1993
        The Regents of the University of California.  All rights reserved.

and

    Copyright (c) 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005,
        2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013
        The NetBSD Foundation, Inc.  All rights reserved.
    Copyright (c) 1982, 1986, 1989, 1991, 1993
        The Regents of the University of California.  All rights reserved.

which causes [issues for packaging in Debian](https://anonscm.debian.org/cgit/pkg-perl/packages/libsystem-info-perl.git/tree/debian/changelog?id=e8145a4d9a60123c2a897e7ec42c833d33115f25).  Could you please clarify the situation?

**Comment by Tux** [comment]
t/etc collects all files that share information on the OS that the
folder describes. This in order to have a test suite that represents
reality. t/etc/get-lsb.pl and t/etc/get-lsb.sh will gether that
information on Linux-like systems, and I store the in the test folder
to use that as fake /etc to analyse the system's release information

Those files represent the copyright as stated on the OS I fetched them
from.

If you have any OS release that is not in that list I really want the
output of get-lsb.pl to make the functioning of this module more
reliable.

As such, these copyright notices have nothing to do with the copyright
of the module System::Info


On Fri, 12 May 2017 03:46:25 -0700, Carnë Draug <notifications@github.com> wrote:

> The `t/etc/netbsd-*/release` have a copyright notice as such:
> 
>     Copyright (c) 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005,
>         2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015
>         The NetBSD Foundation, Inc.  All rights reserved.
>     Copyright (c) 1982, 1986, 1989, 1991, 1993
>         The Regents of the University of California.  All rights reserved.
> 
> and
> 
>     Copyright (c) 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005,
>         2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013
>         The NetBSD Foundation, Inc.  All rights reserved.
>     Copyright (c) 1982, 1986, 1989, 1991, 1993
>         The Regents of the University of California.  All rights reserved.
> 
> which causes [issues for packaging in Debian](https://anonscm.debian.org/cgit/pkg-perl/packages/libsystem-info-perl.git/tree/debian/changelog?id=e8145a4d9a60123c2a897e7ec42c833d33115f25).  Could you please clarify the situation?


-- 
H.Merijn Brand  http://tux.nl   Perl Monger  http://amsterdam.pm.org/
using perl5.00307 .. 5.25   porting perl5 on HP-UX, AIX, and openSUSE
http://mirrors.develooper.com/hpux/        http://www.test-smoke.org/
http://qa.perl.org   http://www.goldmark.org/jeff/stupid-disclaimers/

**Comment by carandraug** [comment]
On 12 May 2017 at 15:54, H.Merijn Brand <notifications@github.com> wrote:
>
> t/etc collects all files that share information on the OS that the
> folder describes. This in order to have a test suite that represents
> reality. t/etc/get-lsb.pl and t/etc/get-lsb.sh will gether that
> information on Linux-like systems, and I store the in the test folder
> to use that as fake /etc to analyse the system's release information
>
> Those files represent the copyright as stated on the OS I fetched them
> from.
>

So `t/etc/netbsd-6.99.24/release` and `t/etc/netbsd-7.99.4/release`
are copies of the files found in NetBSD systems.  From that file only,
NetBSD Foundation claims copyright of those files with "All rights
reserved" which seems would make the file contents non-free.  Would
that file be in a context that specifies its license better?

> If you have any OS release that is not in that list I really want the
> output of get-lsb.pl to make the functioning of this module more
> reliable.
>
> As such, these copyright notices have nothing to do with the copyright
> of the module System::Info
>

Note that the test files are distributed by Debian too in the "source"
packages.  So while this has nothing to do with the copyright of the
System::Info module, it still affects a file distributed and needs to
be free.

**Comment by Tux** [comment]
On Fri, 12 May 2017 09:22:24 -0700, Carnë Draug
<notifications@github.com> wrote:

> On 12 May 2017 at 15:54, H.Merijn Brand <notifications@github.com> wrote:
> >
> > t/etc collects all files that share information on the OS that the
> > folder describes. This in order to have a test suite that represents
> > reality. t/etc/get-lsb.pl and t/etc/get-lsb.sh will gether that
> > information on Linux-like systems, and I store the in the test folder
> > to use that as fake /etc to analyse the system's release information
> >
> > Those files represent the copyright as stated on the OS I fetched them
> > from.  
> 
> So `t/etc/netbsd-6.99.24/release` and `t/etc/netbsd-7.99.4/release`
> are copies of the files found in NetBSD systems.  From that file only,
> NetBSD Foundation claims copyright of those files with "All rights
> reserved" which seems would make the file contents non-free.  Would
> that file be in a context that specifies its license better?

If the contents of those files are a bother, don't ship them in the
release: they are *only* used for testing. If you remove those folders
and the matching lines in MANIFEST, the module will work just the same.

Sorry if I am not very specific, but this is a new area to me.

> > If you have any OS release that is not in that list I really want the
> > output of get-lsb.pl to make the functioning of this module more
> > reliable.
> >
> > As such, these copyright notices have nothing to do with the copyright
> > of the module System::Info
> 
> Note that the test files are distributed by Debian too in the "source"
> packages.  So while this has nothing to do with the copyright of the
> System::Info module, it still affects a file distributed and needs to
> be free.

I am by far an expert on copyright stuff and you made me wonder if the
files that claim the copyright fall under the copyright itself. If that
is true, I'll probably better just remove those tests and files from
the distribution altogether.

And yes, I very much appreciate your feedback and questions. It makes
me more aware of what happens out there. Thank you for your patience.

-- 
H.Merijn Brand  http://tux.nl   Perl Monger  http://amsterdam.pm.org/
using perl5.00307 .. 5.25   porting perl5 on HP-UX, AIX, and openSUSE
http://mirrors.develooper.com/hpux/        http://www.test-smoke.org/
http://qa.perl.org   http://www.goldmark.org/jeff/stupid-disclaimers/

**Comment by carandraug** [comment]
On 12 May 2017 at 18:21, H.Merijn Brand <notifications@github.com> wrote:
>
> On Fri, 12 May 2017 09:22:24 -0700, Carnë Draug
> <notifications@github.com> wrote:
>
> > On 12 May 2017 at 15:54, H.Merijn Brand <notifications@github.com> wrote:
> > >
> > > t/etc collects all files that share information on the OS that the
> > > folder describes. This in order to have a test suite that represents
> > > reality. t/etc/get-lsb.pl and t/etc/get-lsb.sh will gether that
> > > information on Linux-like systems, and I store the in the test folder
> > > to use that as fake /etc to analyse the system's release information
> > >
> > > Those files represent the copyright as stated on the OS I fetched them
> > > from.
> >
> > So `t/etc/netbsd-6.99.24/release` and `t/etc/netbsd-7.99.4/release`
> > are copies of the files found in NetBSD systems. From that file only,
> > NetBSD Foundation claims copyright of those files with "All rights
> > reserved" which seems would make the file contents non-free. Would
> > that file be in a context that specifies its license better?
>
> If the contents of those files are a bother, don't ship them in the
> release: they are *only* used for testing. If you remove those folders
> and the matching lines in MANIFEST, the module will work just the same.
>
> Sorry if I am not very specific, but this is a new area to me.
>
> > > If you have any OS release that is not in that list I really want the
> > > output of get-lsb.pl to make the functioning of this module more
> > > reliable.
> > >
> > > As such, these copyright notices have nothing to do with the copyright
> > > of the module System::Info
> >
> > Note that the test files are distributed by Debian too in the "source"
> > packages. So while this has nothing to do with the copyright of the
> > System::Info module, it still affects a file distributed and needs to
> > be free.
>
> I am by far an expert on copyright stuff and you made me wonder if the
> files that claim the copyright fall under the copyright itself. If that
> is true, I'll probably better just remove those tests and files from
> the distribution altogether.
>
> And yes, I very much appreciate your feedback and questions. It makes
> me more aware of what happens out there. Thank you for your patience.
>

Those files simply claim to be copyrighted and all rights reserved by
the copyright holders.  In the context of the NetBSD distribution, it
doesn't make much sense to me but that's what it is written in the
file.

Maybe this is like those projects where there's a single copyright
notice file and the individual files only have the name of the
copyright holders.  Or maybe they never meant to copyright the file,
instead they are claiming copyright of the whole distribution and you
are supposed to get the actual license from somewhere else.

Could you bring this up with the NetBSD people?  If there is a note
somewhere that says that those files are actually under license X, or
that they are not copyrightable and NetBSD people did not intend to
claim copyright over it, that would solve it.

I can remove that file from the Debian release, but the closer the
Debian package can be to the upstream release the better.

Carnë

**Comment by carandraug** [comment]
I have requested clarification from NetBSD who state that the copyright notice in the file is part of the information about that release. It is not a copyright claim over that file. See http://mail-index.netbsd.org/netbsd-users/2017/07/13/msg019836.html

**Comment by Tux** [comment]
Thank you. Does this mean I can leave that file in?

**Comment by carandraug** [comment]
> Thank you. Does this mean I can leave that file in?

Yes. I left a comment on the debian file explaining the situation and it got accepted. See https://anonscm.debian.org/cgit/pkg-perl/packages/libsystem-info-perl.git/commit/?id=02f03414bdd530c9b87e360b52ef9b7bf90b1f8b

**Comment by Tux** [comment]
Thanks for all the time and effort you put into this! Really appreciated
